name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Prepare, i.e. creates *.c files
        run: |
          pip install cython
          python setup.py prepare

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.10.1
        # env:
        #   CIBW_SOME_OPTION: value
        #    ...
        with:
        #   package-dir: .
        #   output-dir: wheelhouse
           config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl