name: Build wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} and ${{matrix.py}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        py: ['3.10', '3.11']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}

      - name: Prepare, i.e. creates *.c files
        run: |
          python -m pip install cython
          python setup.py prepare

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        # env:
        #   CIBW_SOME_OPTION: value
        #    ...
        with:
        #   package-dir: .
        #   output-dir: wheelhouse
           config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl